spring.application.name=student-management-system

spring.datasource.url=jdbc:postgresql://localhost:5432/student_management
spring.datasource.username=sibbu
spring.datasource.password=Sibbuuuu07

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.formate_sql=true


